### ISSUE TITLE
if __name__ == "__main__":  try: asyncio.run(main())

### ISSUE THREAD

**Issue by Zalovek** [akasakaid/blumtod#105]
![image](https://github.com/user-attachments/assets/91d638da-f0e8-4b67-887e-7052106efb62)
![image](https://github.com/user-attachments/assets/2cdff2c3-3bac-4cc1-87d9-9b3accaa65f0)
![image](https://github.com/user-attachments/assets/09206c8d-245b-46ef-8e77-62bfe7fa6a67)
![image](https://github.com/user-attachments/assets/f3d76f49-28e1-476e-8d54-99ac9aa4cbe0)

**Comment by akasakaid** [comment]
screenshot of the last/bottom part.

**Comment by Zalovek** [comment]
> screenshot of the last/bottom part.

![image](https://github.com/user-attachments/assets/eebd0b30-1ed8-4020-baea-4321c18c47d6)

**Comment by akasakaid** [comment]
wtf not the code man, screenshot your terminal console (the error). screenshot bottom part.

**Comment by Zalovek** [comment]
> wtf not the code man, screenshot your terminal console (the error). screenshot bottom part.

xd i already screenshot all errors in first message

**Comment by akasakaid** [comment]
> > wtf not the code man, screenshot your terminal console (the error). screenshot bottom part.
> 
> xd i already screenshot all errors in first message

Owhh... sorry, I only saw one picture in the first message.

The current version does not support using proxy.

Maybe I will find out the cause later.

**Comment by L4ngx1** [comment]
![image](https://github.com/user-attachments/assets/eca06379-5a23-4b2d-8310-3635659e6ecf)

**Comment by Lastnet0709** [comment]
> ![image](https://private-user-images.githubusercontent.com/189126189/398183765-eca06379-5a23-4b2d-8310-3635659e6ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTk4OTQsIm5iZiI6MTczNTAxOTU5NCwicGF0aCI6Ii8xODkxMjYxODkvMzk4MTgzNzY1LWVjYTA2Mzc5LTVhMjMtNGIyZC04MzEwLTM2MzU2NTllNmVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNTUzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDYxMWFiZjA3ZjhjMjY5MjY0MTQ5MDE0N2EyYzViYmRkZDQ3MTM4ZDA2NWEzODVhZDM3YTZkMmYwYzY0NTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t6Ws-w3Ra7V_Bk_wJdXqYaiIpSuE2J1nI0-ZDT0FrzY)

Downgrading httpx 
`pip install httpx==0.27.2`

**Comment by thanhturau** [comment]
`Traceback (most recent call last):
  File "C:\MMO\blumtod-main\bot.py", line 647, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\MMO\blumtod-main\bot.py", line 625, in main
    res = await BlumTod(
          ^^^^^^^^^^^^^^
  File "C:\MMO\blumtod-main\bot.py", line 226, in start
    await self.ipinfo()
  File "C:\MMO\blumtod-main\bot.py", line 100, in ipinfo
    res = await self.http(ipinfo1_url, headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MMO\blumtod-main\bot.py", line 131, in http
    res = await self.ses.get(url, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1814, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx_socks\_async_transport.py", line 71, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx_socks\_async_proxy.py", line 149, in handle_async_request
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx_socks\_async_proxy.py", line 122, in handle_async_request
    stream = await self._connect_via_proxy(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx_socks\_async_proxy.py", line 159, in _connect_via_proxy
    return await self._open_stream(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx_socks\_async_proxy.py", line 170, in _open_stream
    return await self._open_aio_stream(host, port, connect_timeout, ssl_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx_socks\_async_proxy.py", line 195, in _open_aio_stream
    proxy_stream = await proxy.connect(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\python_socks\async_\anyio\_proxy.py", line 95, in connect
    stream = await stream.start_tls(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\python_socks\async_\anyio\_stream.py", line 45, in start_tls
    ssl_stream = await TLSStream.wrap(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\tls.py", line 132, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\tls.py", line 140, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_CURVE] wrong curve (_ssl.c:1000)`
