### ISSUE TITLE
Multi threading not allowing to play the games

### ISSUE THREAD

**Issue by penpinz** [akasakaid/blumtod#38]
Please solve this error

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/blum/bot.py", line 564, in <module>
    asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/downloads/blum/bot.py", line 556, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/downloads/blum/bot.py", line 327, in start
    point = random.randint(self.cfg.low, self.cfg.high)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/random.py", line 362, in randint
    return self.randrange(a, b+1)
                             ~^~
TypeError: can only concatenate str (not "int") to str

**Comment by akasakaid** [comment]
Try to remove config.json file, and re run the script bot.

**Comment by penpinz** [comment]
> Try to remove config.json file, and re run the script bot.

Same error persists

**Comment by akasakaid** [comment]
> > Try to remove config.json file, and re run the script bot.
> 
> Same error persists

Try to update,

**Comment by penpinz** [comment]
> > > Try to remove config.json file, and re run the script bot.
> > 
> > 
> > Same error persists
> 
> Try to update,

Issue cleared. Please give your telegram channel/chat group. Will support you. You doing a awesome job for us all.

**Comment by November8** [comment]
Traceback (most recent call last):
  File "E:\blumtod-main1222\bot.py", line 564, in <module>
    asyncio.run(main())
  File "E:\Python3.12.5\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\blumtod-main1222\bot.py", line 556, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blumtod-main1222\bot.py", line 213, in start
    res = await self.http(checkin_url, self.headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blumtod-main1222\bot.py", line 124, in http
    res = await self.ses.get(url, headers=headers, timeout=30)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx\_client.py", line 1801, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx_socks\_async_transport.py", line 72, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "E:\Python3.12.5\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx_socks\_async_proxy.py", line 120, in handle_async_request
    stream = await self._connect_via_proxy(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx_socks\_async_proxy.py", line 154, in _connect_via_proxy
    return await self._open_stream(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx_socks\_async_proxy.py", line 165, in _open_stream
    return await self._open_aio_stream(host, port, connect_timeout, ssl_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\httpx_socks\_async_proxy.py", line 190, in _open_aio_stream
    proxy_stream = await proxy.connect(
                   ^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\python_socks\async_\anyio\_proxy.py", line 88, in connect
    await connector.connect(
  File "E:\Python3.12.5\Lib\site-packages\python_socks\_connectors\socks5_async.py", line 42, in connect
    data = await stream.read_exact(socks5.AuthMethodReply.SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\python_socks\async_\anyio\_stream.py", line 34, in read_exact
    packet = await self.read(n - len(data))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\python_socks\async_\anyio\_stream.py", line 27, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python3.12.5\Lib\site-packages\anyio\_backends\_asyncio.py", line 1153, in receive
    raise self._protocol.exception from None
anyio.BrokenResourceError

**Comment by akasakaid** [comment]
Try to limit your worker use `python bot.py --worker 1`
