### ISSUE TITLE
game play

### ISSUE THREAD

**Issue by nguyenanh29** [akasakaid/blumtod#41]
It can't play the game, comes with errors
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/anh/blumtod/bot.py", line 556, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by akasakaid** [comment]
Please take a screenshot.

**Comment by nguyenanh29** [comment]
![image](https://github.com/user-attachments/assets/ab8d79bb-b708-4631-b3f1-b6df7b7d8c07)
![Screenshot 2024-09-18 170758](https://github.com/user-attachments/assets/1412c93a-03b7-428d-b99e-c2cd7e94a2aa)
Here is the screenshot of issue

**Comment by abrorbekqakhkhorov** [comment]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\blumtod\bot.py", line 571, in <module>
    asyncio.run(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\blumtod\bot.py", line 563, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\blumtod\bot.py", line 237, in start
    refres = await self.http(friend_balance_url, self.headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\blumtod\bot.py", line 131, in http
    async with aiofiles.open(log_file, "a", encoding="utf-8") as hw:
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiofiles\base.py", line 63, in __aenter__
    return await self
           ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiofiles\base.py", line 59, in __await__
    self._obj = yield from self._coro.__await__()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiofiles\threadpool\__init__.py", line 92, in _open
    f = await loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'http.log'

**Comment by nguyenanh29** [comment]
> Please take a screenshot.

i sent the screenshots couple hours ago. by the i am typing, i have done git pull to update and it works like a charm! Thanks so much for awesome works!
