### ISSUE TITLE
error

### ISSUE THREAD

**Issue by luksiko** [akasakaid/blumtod#59]
```
Traceback (most recent call last):
  File "/Users/alexeyvassilyev/Sites/blumtod/bot.py", line 622, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/alexeyvassilyev/Sites/blumtod/bot.py", line 600, in main
    res = await BlumTod(
          ^^^^^^^^^^^^^^
  File "/Users/alexeyvassilyev/Sites/blumtod/bot.py", line 220, in start
    result = await get_by_id(uid)
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexeyvassilyev/Sites/blumtod/models.py", line 76, in get_by_id
    "useragent": result["useragent"],
                 ~~~~~~^^^^^^^^^^^^^
IndexError: No item with that key
```

**Comment by kiethopt** [comment]
same
