### ISSUE TITLE
erorr bang 

### ISSUE THREAD

**Issue by weck25** [akasakaid/blumtod#60]
[20:26:42]-[acc 1] login as Sizzle
Traceback (most recent call last):
  File "/root/blumtod/bot.py", line 622, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/blumtod/bot.py", line 591, in main
    result = await asyncio.gather(*tasks)
  File "/root/blumtod/bot.py", line 583, in bound
    return await BlumTod(*params).start()
  File "/root/blumtod/bot.py", line 220, in start
    result = await get_by_id(uid)
  File "/root/blumtod/models.py", line 76, in get_by_id
    "useragent": result["useragent"],
IndexError: No item with that key
root@ubuntu-s-1vcpu-2gb-70gb-intel-nyc1-01:~/blumtod#

**Comment by painterzeou** [comment]
https://github.com/akasakaid/blumtod#how-to-update

Read how to update
