### ISSUE TITLE
error

### ISSUE THREAD

**Issue by reysilvano78** [akasakaid/blumtod#62]
1.) set on/off auto claim (active)                                2.) set on/off auto solve task (active)                           3.) set on/off auto play game (active)
    4.) set game point (240-250)                                      5.) set wait time before start (30-60)                            6.) start bot (multiprocessing)
    7.) start bot (sync mode)                                                                                                       input number : 7
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                [09:39:10]-[acc 1] ip : 45.127.248.127 country : US               [09:39:10]-[acc 1] login as R 🦴🆓
Traceback (most recent call last):                                  File "/storage/emulated/0/bot/daily/blumtod/blumtod/bot.py", line 622, in <module>
    asyncio.run(main())                                             File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)                                                  ^^^^^^^^^^^^^^^^                                         File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run                                            return self._loop.run_until_complete(task)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete                         return future.result()
           ^^^^^^^^^^^^^^^
  File "/storage/emulated/0/bot/daily/blumtod/blumtod/bot.py", line 600, in main
    res = await BlumTod(
          ^^^^^^^^^^^^^^
  File "/storage/emulated/0/bot/daily/blumtod/blumtod/bot.py", line 220, in start
    result = await get_by_id(uid)
             ^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/bot/daily/blumtod/blumtod/models.py", line 76, in get_by_id
    "useragent": result["useragent"],
                 ~~~~~~^^^^^^^^^^^^^
IndexError: No item with that key

**Comment by akasakaid** [comment]
https://github.com/akasakaid/blumtod/issues/61#issuecomment-2378027766
