### ISSUE TITLE
error useragent

### ISSUE THREAD

**Issue by dashcappitain** [akasakaid/blumtod#72]
![CleanShot 2024-09-30 at 12 14 18@2x](https://github.com/user-attachments/assets/d40d4e08-a094-441d-89f9-ee4110481391)

[12:12:52]-[acc 1] ip : 104.239.53.144 country : US
[12:12:52]-[acc 1] login as 51 🍅
Traceback (most recent call last):
  File "/mnt/e/bot/blum-akasaka/bot.py", line 623, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/mnt/e/bot/blum-akasaka/bot.py", line 601, in main
    res = await BlumTod(
          ^^^^^^^^^^^^^^
  File "/mnt/e/bot/blum-akasaka/bot.py", line 220, in start
    result = await get_by_id(uid)
             ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/bot/blum-akasaka/models.py", line 76, in get_by_id
    "useragent": result["useragent"],
                 ~~~~~~^^^^^^^^^^^^^
IndexError: No item with that key


ini kenapa ya om?

**Comment by akasakaid** [comment]
[Cara melakukan update](https://github.com/akasakaid/blumtod/blob/main/README_ID.md#cara-melakukan-update)

**Comment by dashcappitain** [comment]
thanks udah bisa om
