### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by OrrnobMahmud** [akasakaid/blumtod#8]
Traceback (most recent call last):
  File "C:\Users\User\blumtod\bot.py", line 368, in <module>
    app.main()
  File "C:\Users\User\blumtod\bot.py", line 343, in main
    self.solve_task(access_token)
  File "C:\Users\User\blumtod\bot.py", line 66, in solve_task
    task_id = task["id"]
KeyError: 'id'
PS C:\Users\User\blumtod>

**Comment by akasakaid** [comment]
i already update it. check it for new version !
