### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by argoarsiks** [akasakaid/blumtod#82]
Traceback (most recent call last):
  File "C:\Users\PC.DESKTOP-55VNAR1\Desktop\pix\blumtod\bot.py", line 622, in <module>
    asyncio.run(main())
  File "C:\Users\PC.DESKTOP-55VNAR1\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\PC.DESKTOP-55VNAR1\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC.DESKTOP-55VNAR1\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC.DESKTOP-55VNAR1\Desktop\pix\blumtod\bot.py", line 591, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC.DESKTOP-55VNAR1\Desktop\pix\blumtod\bot.py", line 583, in bound
    return await BlumTod(*params).start()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC.DESKTOP-55VNAR1\Desktop\pix\blumtod\bot.py", line 226, in start
    useragent = UserAgent(os=["android", "ios", "windows"]).random
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FakeUserAgent.__init__() got an unexpected keyword argument 'os'

**Comment by Mrhmn** [comment]
Traceback (most recent call last):
  File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 622, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 600, in main
    res = await BlumTod(
          ^^^^^^^^^^^^^^
  File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 346, in start
    game_id = res.json().get("gameId")
              ^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Mrhmn** [comment]
> Traceback (most recent call last): File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 622, in asyncio.run(main()) File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 600, in main res = await BlumTod( ^^^^^^^^^^^^^^ File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 346, in start game_id = res.json().get("gameId") ^^^^^^^^^^ File "C:\Program Files\Python311\Lib\site-packages\httpx_models.py", line 756, in json return jsonlib.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

what should i do ?
