### ISSUE TITLE
JSONDecodeError("Expecting value", s, err.value)

### ISSUE THREAD

**Issue by Mrhmn** [akasakaid/blumtod#83]
Full Error :

Traceback (most recent call last):
  File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 622, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 600, in main
    res = await BlumTod(
          ^^^^^^^^^^^^^^
  File "C:\Users\HMN\Desktop\New Blum\blumtod-main\bot.py", line 346, in start
    game_id = res.json().get("gameId")
              ^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by akasakaid** [comment]
Translate to your language : https://t.me/sdsproject_chat/178605

**Comment by Erkinovich-fx** [comment]
Same error


Traceback (most recent call last):
  File "/storage/emulated/0/Download/blumtod/bot.py", line 622, in <module>
    asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Download/blumtod/bot.py", line 591, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Download/blumtod/bot.py", line 583, in bound
    return await BlumTod(*params).start()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Download/blumtod/bot.py", line 346, in start
    game_id = res.json().get("gameId")
              ^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Danny972** [comment]
Тоже самое бро

**Comment by akasakaid** [comment]
> Same error
> 
> 
> Traceback (most recent call last):
>   File "/storage/emulated/0/Download/blumtod/bot.py", line 622, in <module>
>     asyncio.run(main())
>   File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/storage/emulated/0/Download/blumtod/bot.py", line 591, in main
>     result = await asyncio.gather(*tasks)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/storage/emulated/0/Download/blumtod/bot.py", line 583, in bound
>     return await BlumTod(*params).start()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/storage/emulated/0/Download/blumtod/bot.py", line 346, in start
>     game_id = res.json().get("gameId")
>               ^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/httpx/_models.py", line 766, in json
>     return jsonlib.loads(self.content, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.12/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.12/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Ref : https://github.com/akasakaid/blumtod/issues/83#issuecomment-2408305122
