### ISSUE TITLE
it can't play game

### ISSUE THREAD

**Issue by dj98986** [akasakaid/blumtod#90]
[20:29:12]-[acc 1] you have 14 game ticket
Traceback (most recent call last):
  File "C:\Users\pjsm\Downloads\blumtod-main (2)\blumtod-main\bot.py", line 622, in <module>
    asyncio.run(main())
  File "C:\Users\pjsm\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\pjsm\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pjsm\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\pjsm\Downloads\blumtod-main (2)\blumtod-main\bot.py", line 591, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pjsm\Downloads\blumtod-main (2)\blumtod-main\bot.py", line 583, in bound
    return await BlumTod(*params).start()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pjsm\Downloads\blumtod-main (2)\blumtod-main\bot.py", line 346, in start
    game_id = res.json().get("gameId")
              ^^^^^^^^^^
  File "C:\Users\pjsm\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pjsm\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pjsm\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pjsm\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by akasakaid** [comment]
Translate https://t.me/sdsproject/140 from indonesian to your language.
