### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by xMacoy01** [akasakaid/blumtod#92]
Traceback (most recent call last):
  File "C:\Users\xAstrid\Desktop\blumtod-main\bot.py", line 622, in <module>
    asyncio.run(main())
  File "C:\Users\xAstrid\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xAstrid\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xAstrid\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\xAstrid\Desktop\blumtod-main\bot.py", line 591, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xAstrid\Desktop\blumtod-main\bot.py", line 583, in bound
    return await BlumTod(*params).start()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xAstrid\Desktop\blumtod-main\bot.py", line 346, in start
    game_id = res.json().get("gameId")
              ^^^^^^^^^^
  File "C:\Users\xAstrid\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xAstrid\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xAstrid\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xAstrid\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by akasakaid** [comment]
Ref https://github.com/akasakaid/blumtod/issues/91#issuecomment-2408824323
