### ISSUE TITLE
Error, does't complete games, breaks

### ISSUE THREAD

**Issue by luksiko** [akasakaid/blumtod#93]
error after  set on/off auto play game **active**

`Traceback (most recent call last):
File "/Users/Sites/blumtod/bot.py", line 622, in <module>
    asyncio.run(main())
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
    ^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
    ^^^^^^^^^^^^^^^
    File "/Users/Sites/blumtod/bot.py", line 591, in main
    result = await asyncio.gather(*tasks)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/Sites/blumtod/bot.py", line 583, in bound
    return await BlumTod(*params).start()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/Sites/blumtod/bot.py", line 346, in start
    game_id = res.json().get("gameId")
    ^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by 181011** [comment]
got the same error

**Comment by nguyenanh29** [comment]
same error.

**Comment by yahia912** [comment]
Same

**Comment by akasakaid** [comment]
Here https://github.com/akasakaid/blumtod/issues/92#issuecomment-2408881177
