### ISSUE TITLE
Please 🙏 i need help

### ISSUE THREAD

**Issue by Ramo003** [akasakaid/blumtod#94]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/blumtod/bot.py", line 622, in <module>
    asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/blumtod/bot.py", line 600, in main
    res = await BlumTod(
          ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/blumtod/bot.py", line 346, in start
    game_id = res.json().get("gameId")
              ^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by akasakaid** [comment]
Here https://github.com/akasakaid/blumtod/issues/92#issuecomment-2408881177
