### ISSUE TITLE
Error json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by chokisoklat** [akasakaid/blumtod#95]
can you fix it?

Traceback (most recent call last):
  File "/home/kuda/Downloads/cryptobot/blumtod-main/bot.py", line 622, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/kuda/Downloads/cryptobot/blumtod-main/bot.py", line 591, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kuda/Downloads/cryptobot/blumtod-main/bot.py", line 583, in bound
    return await BlumTod(*params).start()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kuda/Downloads/cryptobot/blumtod-main/bot.py", line 346, in start
    game_id = res.json().get("gameId")
              ^^^^^^^^^^
  File "/home/kuda/Downloads/cryptobot/blumtod-main/lib/python3.12/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by akasakaid** [comment]
Here https://github.com/akasakaid/blumtod/issues/93#issuecomment-2410801268
